sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.120.38.185
    port: 3306
    database: sky_take_out
    username: bronya
    password: bronya
  alioss:
    access-key-secret:  HtPc1kI0Pibr0dXFrJUxS0AG5Qk3mX
    access-key-id: LTAI5t6kcRwzYocvEwTyN9sw
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: take-out11
 #redis
  redis:
    host: 47.120.38.185
    port: 6379
    password: bronya
    database: 2