sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.120.38.185
    port: 3306
    database: sky_take_out
    username: bronya
    password: bronya
  alioss:
    access-key-secret:  VWvUMbTVrFKftEiASTRhTWssV1Y59g
    access-key-id: LTAI5tNhy8BCzZ6ouJDtDuVh
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: take-out11