sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 你自己的数据库ip
    port: 端口
    database: 自己的数据库名
    username: username
    password: password
  alioss:
    access-key-secret:  你自己的access-key-secret
    access-key-id: 你自己的access-key-id
    endpoint:
    bucket-name:
 #redis
  redis:
    host:
    port:
    password: 
    database:
  wechat:
    appid:
    secret: